name: Coverage

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  run_coverage:
    runs-on: ubuntu-latest
    permissions: 
      contents: write

    steps:
    - uses: actions/checkout@v4
      with:
          ref: ${{ github.head_ref }}
    - name: Install Tarpaulin
      run: |
        cd server
        cargo install cargo-tarpaulin
    - name: Generate Coverage
      run: |
        cd server
        cargo tarpaulin --out=html
    - name: Commit coverage report
      run: |
        cd server
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add tarpaulin-report.html
        git commit -m "Auto update" || echo "No changes"
        git push
